import { readdirSync, readFileSync, statSync } from 'fs'
import path from 'path'

const ROOT = path.resolve(import.meta.dirname!, '..')
const PUBLIC_DIR = path.join(ROOT, 'src', 'public')
const OUTPUT_FILE = path.join(ROOT, 'src', 'public-embedded.ts')

function scanDir(dir: string, base: string): Record<string, string> {
  const files: Record<string, string> = {}
  const entries = readdirSync(dir)

  for (const entry of entries) {
    const fullPath = path.join(dir, entry)
    const relativePath = path.posix.join(base, entry)
    const stats = statSync(fullPath)

    if (stats.isDirectory()) {
      Object.assign(files, scanDir(fullPath, relativePath))
    } else {
      const content = readFileSync(fullPath)
      files[relativePath] = content.toString('base64')
    }
  }

  return files
}

const files = scanDir(PUBLIC_DIR, '')

const output = `// Auto-generated by scripts/generate-public-embedded.ts
// Contains the base64-encoded contents of src/public so the standalone
// executable can reconstruct them on disk at runtime.

export const PUBLIC_FILES: Record<string, string> = ${JSON.stringify(files, null, 2)}
`

import('fs').then(({ writeFileSync }) => {
  writeFileSync(OUTPUT_FILE, output)
  console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(files).length} files`)
})
