import { readFileSync, writeFileSync } from 'fs'
import path from 'path'

const vigemDir = path.resolve('node_modules', 'vigemclient')
const files = [
  'package.json',
  'index.js',
  'lib/common.js',
  'lib/ViGEmClient.js',
  'lib/ViGEmTarget.js',
  'lib/X360Controller.js',
  'lib/X360ControllerReport.js',
  'lib/DS4Controller.js',
  'lib/DS4ControllerReport.js',
  'lib/DS4ControllerExtendedReport.js',
  'lib/InputAxis.js',
  'lib/InputButton.js'
]

const entries: Record<string, string> = {}
for (const file of files) {
  const content = readFileSync(path.join(vigemDir, file), 'utf-8')
  entries[file] = content
}

const output = `// Auto-generated by scripts/generate-vigem-embedded.ts
// Contains the JS source of the vigemclient package so it can be reconstructed
// on disk when running from a bun build --compile executable.

export const VIGEM_FILES: Record<string, string> = ${JSON.stringify(entries, null, 2)}
`

writeFileSync(path.resolve('src', 'vigem-embedded.ts'), output)
console.log('Generated src/vigem-embedded.ts')
